### ISSUE TITLE
Why do FPO.head and FPO.tail operate on Objects?

### ISSUE THREAD

**Issue by christianhg** [getify/fpo#8]
Since property order is not guaranteed on Objects, does it even make sense to ask for their head or tail?

**Comment by getify** [comment]
`head(..)` and `tail(..)` interpret themselves on objects to mean grabbing a property named `0` for the `head(..)`, or anything except such a `0` property for `tail(..)`. This is primarily so that `arguments` (or other array-like objects) work rationally even without being transformed to an array.

There are a couple of other methods in the API that work on object properties in an "ordered" way, like `reduceObj(..)` and `curry(..)` (it's strict and should take the "first" property from each object argument). For these the docs clearly state they use "enumeration order" (`Object.keys(..)`), and also warn that while this is relatively well supported, it's not strictly guaranteed cross-platform.

**Comment by getify** [comment]
Closing for now. If you have any more comments or questions, feel free to add them.
